{{- if eq .Values.engine "medusa" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ecommerce-store.fullname" . }}-medusa
  labels:
    {{- include "ecommerce-store.medusa.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ include "ecommerce-store.ingressHost" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ecommerce-store.medusa.serviceName" . }}
                port:
                  name: http
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ include "ecommerce-store.ingressHost" . }}
      {{- if .Values.ingress.tlsSecretName }}
      secretName: {{ .Values.ingress.tlsSecretName }}
      {{- end }}
  {{- end }}
{{- end }}
