{{- if eq .Values.engine "medusa" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-store.medusa.secretName" . }}
  labels:
    {{- include "ecommerce-store.medusa.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-email: {{ .Values.medusa.admin.email | default "admin@example.com" | quote }}
  admin-password: {{ .Values.medusa.admin.password | default "supersecret" | quote }}
  jwt-secret: {{ .Values.medusa.jwtSecret | default "supersecret-jwt" | quote }}
  cookie-secret: {{ .Values.medusa.cookieSecret | default "supersecret-cookie" | quote }}
{{- end }}
