{{- if eq .Values.engine "medusa" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-store.medusa.serviceName" . }}
  labels:
    {{- include "ecommerce-store.medusa.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ecommerce-store.medusa.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-store.fullname" . }}-medusa-db
  labels:
    {{- include "ecommerce-store.medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  # Headless service for StatefulSet
  clusterIP: None
  ports:
    - port: 5432
      targetPort: pg
      protocol: TCP
      name: pg
  selector:
    {{- include "ecommerce-store.medusa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
