{{- if and (eq .Values.engine "medusa") .Values.storefront.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-store.storefront.serviceName" . }}
  labels:
    {{- include "ecommerce-store.storefront.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ecommerce-store.storefront.selectorLabels" . | nindent 4 }}
{{- end }}
