{{- if eq .Values.engine "woocommerce" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-store.wordpress.secretName" . }}
  labels:
    {{- include "ecommerce-store.wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  admin-username: {{ .Values.wordpress.admin.username | b64enc | quote }}
  admin-password: {{ .Values.wordpress.admin.password | b64enc | quote }}
  admin-email: {{ .Values.wordpress.admin.email | b64enc | quote }}
{{- end }}
