{{- if eq .Values.engine "woocommerce" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-store.wordpress.serviceName" . }}
  labels:
    {{- include "ecommerce-store.wordpress.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ecommerce-store.wordpress.selectorLabels" . | nindent 4 }}
{{- end }}
