{{- if eq .Values.engine "woocommerce" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-store.mariadb.serviceName" . }}
  labels:
    {{- include "ecommerce-store.mariadb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "ecommerce-store.mariadb.selectorLabels" . | nindent 4 }}
{{- end }}
